# Generated by Django 3.0.7 on 2021-03-14 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(help_text='From:', max_length=100)),
                ('contains', models.CharField(help_text='From:', max_length=100)),
                ('folder', models.CharField(help_text='Folder to file into', max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mailbox', models.ForeignKey(help_text='From:', on_delete=django.db.models.deletion.CASCADE, to='accounts.MailUser')),
            ],
            options={
                'ordering': ['mailbox', 'folder', 'contains', 'field'],
                'unique_together': {('mailbox', 'field', 'contains', 'folder')},
            },
        ),
    ]
