# Generated by Django 3.0.7 on 2021-03-14 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.Mailbox')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('from_address', models.CharField(max_length=256, verbose_name='From')),
                ('to_address', models.CharField(max_length=4096, verbose_name='To')),
                ('cc', models.CharField(blank=True, max_length=4096, null=True, verbose_name='CC')),
                ('bcc', models.CharField(blank=True, max_length=4096, null=True, verbose_name='BCC')),
                ('subject', models.CharField(max_length=256, verbose_name='Subject')),
                ('body', models.TextField(verbose_name='Body')),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.Mailbox')),
            ],
        ),
        migrations.CreateModel(
            name='Envelope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=256, verbose_name='Message-ID')),
                ('sender', models.CharField(max_length=256, verbose_name='Sender')),
                ('receiver', models.CharField(max_length=4096, verbose_name='Receiver')),
                ('msg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mail.Message')),
            ],
        ),
    ]
